#!/usr/bin/env node
/**
 * Objective asset audit for BikeBrowser (no beauty judgment — facts only).
 * Checks: dimensions, file type, alpha channel, placeholder naming, resolution
 * outliers, manifest references (missing files), and draft-status runtime loading.
 * Output: artifacts/bikebrowser/asset_audit_latest.md
 *
 * Dependency-free: PNG dimensions/color-type parsed from the IHDR header.
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, extname, relative } from 'node:path';

const ROOT = process.cwd();
const ASSET_DIRS = ['public', 'src/game/art'].map((d) => join(ROOT, d)).filter(existsSync);
const MANIFEST = join(ROOT, 'src/game/data/act1/act1AssetManifest.js');
const OUT = join(ROOT, 'artifacts/bikebrowser/asset_audit_latest.md');
const PLACEHOLDER_RE = /(draft|placeholder|stub|tmp|_wip|temp)/i;
const IMG_EXT = new Set(['.png', '.jpg', '.jpeg', '.webp', '.svg']);

function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const s = statSync(p);
    if (s.isDirectory()) walk(p, acc);
    else acc.push(p);
  }
  return acc;
}

function pngInfo(buf) {
  // signature + IHDR
  if (buf.length < 26 || buf[0] !== 0x89 || buf[1] !== 0x50) return null;
  const width = buf.readUInt32BE(16);
  const height = buf.readUInt32BE(20);
  const colorType = buf[25]; // 2=RGB,6=RGBA,4=GA,0=gray,3=indexed
  const hasAlpha = colorType === 4 || colorType === 6;
  return { width, height, colorType, hasAlpha };
}

const issues = { placeholderNamed: [], notImage: [], zeroByte: [], noAlphaSprite: [], resolutionOutlier: [], manifestMissing: [], draftStatus: [] };
let imgCount = 0;

// 1) Walk asset dirs
for (const dir of ASSET_DIRS) {
  for (const file of walk(dir)) {
    const ext = extname(file).toLowerCase();
    const rel = relative(ROOT, file).replace(/\\/g, '/');
    const size = statSync(file).size;
    if (!IMG_EXT.has(ext)) continue;
    imgCount++;
    if (size === 0) issues.zeroByte.push(rel);
    if (PLACEHOLDER_RE.test(rel)) issues.placeholderNamed.push(rel);
    if (ext === '.svg') issues.notImage.push(`${rel} (SVG in asset path — should be rasterized pixel art)`);
    if (ext === '.png') {
      const info = pngInfo(readFileSync(file));
      if (info) {
        const isSprite = /character|sprite|sheet|npc|icon|cue/i.test(rel);
        if (isSprite && !info.hasAlpha) issues.noAlphaSprite.push(`${rel} (${info.width}x${info.height}, colorType ${info.colorType})`);
        if (info.width > 4096 || info.height > 4096) issues.resolutionOutlier.push(`${rel} (${info.width}x${info.height} — very large)`);
        if (info.width < 8 || info.height < 8) issues.resolutionOutlier.push(`${rel} (${info.width}x${info.height} — very small)`);
      }
    }
  }
}

// 2) Manifest cross-reference (missing files + draft-status runtime check)
if (existsSync(MANIFEST)) {
  const txt = readFileSync(MANIFEST, 'utf8');
  const finalPaths = [...txt.matchAll(/finalPath:\s*'([^']+)'/g)].map((m) => m[1]);
  for (const p of finalPaths) {
    const abs = join(ROOT, p);
    if (!existsSync(abs)) issues.manifestMissing.push(p);
  }
  const draftBlocks = [...txt.matchAll(/status:\s*'draft'/g)];
  if (draftBlocks.length) {
    // Loader gate: loadAct1FinalAssets loads only 'final_ready' (P0). Confirm.
    const reg = readFileSync(join(ROOT, 'src/game/phaser/systems/AssetRegistry.js'), 'utf8');
    const loadsDraft = /\.includes\(asset\.status\).*draft/.test(reg) || /asset\.status\s*!==\s*'final_ready'/.test(reg) === false;
    issues.draftStatus.push(`${draftBlocks.length} manifest entries are status:'draft'. Loader loads only final_ready: ${/asset\.status\s*!==\s*'final_ready'/.test(reg) ? 'YES (drafts excluded ✓)' : 'CHECK'}`);
  }
}

function section(title, arr, ok = 'none') {
  if (!arr.length) return `### ${title}\n- ${ok}\n`;
  return `### ${title} (${arr.length})\n` + arr.map((x) => `- ${x}`).join('\n') + '\n';
}

const report = `# Asset Audit (automated, objective) — BikeBrowser

Generated by \`scripts/art/asset_audit.mjs\`. Facts only; no beauty judgment.
Images scanned: **${imgCount}** across ${ASSET_DIRS.map((d) => relative(ROOT, d)).join(', ')}.

${section('Zero-byte files', issues.zeroByte)}
${section('Placeholder-named assets (draft/placeholder/stub/tmp/wip)', issues.placeholderNamed)}
${section('SVG files in asset paths (should be rasterized pixel)', issues.notImage)}
${section('Sprites missing an alpha channel', issues.noAlphaSprite)}
${section('Resolution outliers (>4096 or <8 px)', issues.resolutionOutlier)}
${section('Manifest finalPath files MISSING on disk', issues.manifestMissing)}
${section('Draft-status manifest entries (runtime-load check)', issues.draftStatus)}

> Interpretation: placeholder-named + SVG-in-asset-path entries are the
> consolidation backlog (see asset_upgrade_queue.md). Draft entries should NOT be
> loaded at runtime (P0 loader loads only \`final_ready\`). Missing manifest files
> would cause load errors and must be fixed before release.
`;

writeFileSync(OUT, report);
console.log(`Asset audit written: ${relative(ROOT, OUT)}`);
console.log(`images=${imgCount} placeholderNamed=${issues.placeholderNamed.length} svgInPath=${issues.notImage.length} missingManifest=${issues.manifestMissing.length}`);
