export const LETTER_DETECTIVE_PAIRS = [
  { lower: 'b', upper: 'B', sound: '/b/', confusableGroup: 'bdpq' },
  { lower: 'd', upper: 'D', sound: '/d/', confusableGroup: 'bdpq' },
  { lower: 'p', upper: 'P', sound: '/p/', confusableGroup: 'bdpq' },
  { lower: 'q', upper: 'Q', sound: '/kw/', confusableGroup: 'bdpq' },
];

export const LETTER_DETECTIVE_MODES = [
  {
    id: 'case-match',
    title: 'Case Match',
    prompt: 'Find the lowercase match for B',
    target: 'b',
    answer: 'b',
    options: ['b', 'd', 'p', 'q'],
    feedback: 'Nice - B matches b.',
    explanation: 'That was {choice}. B matches b.',
    soundPrompt: 'Find lowercase b.',
    confusablePair: 'B->b',
  },
  {
    id: 'capital-match',
    title: 'Capital Match',
    prompt: 'Find the uppercase match for d',
    target: 'D',
    answer: 'D',
    options: ['B', 'D', 'P', 'Q'],
    feedback: 'Nice - d matches D.',
    explanation: 'That was {choice}. d matches D.',
    soundPrompt: 'Find uppercase D.',
    confusablePair: 'd->D',
  },
  {
    id: 'mirror-hunter',
    title: 'Mirror Hunter',
    prompt: 'Find b',
    target: 'b',
    answer: 'b',
    options: ['d', 'd', 'p', 'b', 'q', 'd'],
    feedback: 'Nice - you found b.',
    explanation: 'That was {choice}. The target is b.',
    soundPrompt: 'Find b.',
    confusablePair: 'b->d',
  },
  {
    id: 'sound-match',
    title: 'Sound Match',
    prompt: 'Find the letter that says /b/',
    target: 'b',
    answer: 'b',
    options: ['b', 'd', 'p'],
    feedback: 'Nice - b says /b/.',
    explanation: 'That was {choice}. b says /b/.',
    soundPrompt: 'Find the letter that says buh.',
    confusablePair: 'b->d',
  },
];
