// Engine configs for the dyno (Chapter 3). New domain (motorcycle engines), so
// these are first-class config — same data-driven pattern as the UTM materials:
// adding an engine is a new entry here, no code change.
export const ENGINES = [
  {
    id: 'cafe_racer_parallel_twin',
    name: 'Parallel Twin 650cc',
    category: 'Street',
    color: '#C0392B',
    displacement: 649,
    maxRPM: 10500,
    redlineRPM: 9500,
    idleRPM: 900,
    peakTorque: 64,
    peakTorqueRPM: 5500,
    peakPower: 47,
    peakPowerRPM: 7500,
    bikeWeight: 193,
    curveParams: { torquePeakWidth: 0.35, powerDropSharpness: 0.6 },
    engineSound: 'parallel_twin',
  },
  {
    id: 'enduro_single',
    name: 'Single Cylinder 450cc',
    category: 'Off-Road',
    color: '#E67E22',
    displacement: 449,
    maxRPM: 11000,
    redlineRPM: 10200,
    idleRPM: 1200,
    peakTorque: 51,
    peakTorqueRPM: 6800,
    peakPower: 38,
    peakPowerRPM: 8500,
    bikeWeight: 110,
    curveParams: { torquePeakWidth: 0.28, powerDropSharpness: 0.75 },
    engineSound: 'single_cylinder',
  },
  {
    id: 'cruiser_v_twin',
    name: 'V-Twin 1200cc',
    category: 'Cruiser',
    color: '#2980B9',
    displacement: 1202,
    maxRPM: 6500,
    redlineRPM: 6000,
    idleRPM: 700,
    peakTorque: 98,
    peakTorqueRPM: 3200,
    peakPower: 52,
    peakPowerRPM: 4800,
    bikeWeight: 295,
    curveParams: { torquePeakWidth: 0.45, powerDropSharpness: 0.5 },
    engineSound: 'v_twin',
  },
  {
    id: 'supersport_inline4',
    name: 'Inline-4 1000cc',
    category: 'Sport',
    color: '#8E44AD',
    displacement: 998,
    maxRPM: 14500,
    redlineRPM: 13500,
    idleRPM: 1000,
    peakTorque: 113,
    peakTorqueRPM: 9500,
    peakPower: 147,
    peakPowerRPM: 12000,
    bikeWeight: 199,
    curveParams: { torquePeakWidth: 0.30, powerDropSharpness: 0.8 },
    engineSound: 'inline_four',
  },
];

export const ENGINES_BY_ID = Object.fromEntries(ENGINES.map((e) => [e.id, e]));
export const getEngineById = (id) => ENGINES_BY_ID[id] || null;
